- name: Check if mosquitto is already installed
  shell: dpkg-query -W -f=${Status} mosquitto 2>/dev/null | grep -c "ok installed"
  register: mosquitto_installed
  changed_when: false

- name: Add the Mosquitto PPA
  apt_repository:
    repo: "ppa:mosquitto-dev/mosquitto-ppa"
    state: present
  when: mosquitto_installed.stdout == "0" and ansible_distribution == 'Ubuntu'
  register: ppa_added

- name: Update apt cache if repository was added
  apt:
    update_cache: yes
  when: ppa_added.changed

- name: Install mosquitto and mosquitto-clients
  apt:
    name:
      - mosquitto
      - mosquitto-clients
    state: present
  when: mosquitto_installed.stdout == "0" and ansible_distribution == 'Ubuntu'

- name: Copy mosquitto configuration file
  copy:
    src: mosquitto.conf
    dest: /path/where/you/want/mosquitto.conf
    owner: root
    group: root
    mode: "0644"
  when: mosquitto_installed.stdout == "0"
  notify: restart mosquitto

- name: Ensure mosquitto is enabled and started
  service:
    name: mosquitto
    enabled: yes
    state: started
  when: mosquitto_installed.stdout == "0"
