- name: Check if Mosquitto is installed
  become: true
  command: dpkg -s mosquitto
  register: mosquitto_package_status
  changed_when: false
  failed_when: false

- name: Add the Mosquitto PPA
  apt_repository:
    repo: "ppa:mosquitto-dev/mosquitto-ppa"
    state: present
  when: mosquitto_package_status.rc != 0 and ansible_distribution == 'Ubuntu'
  register: ppa_added

- name: Update apt cache if repository was added
  apt:
    update_cache: yes
  when: mosquitto_package_status.rc != 0 and ppa_added.changed

- name: Install mosquitto and mosquitto-clients
  apt:
    name:
      - mosquitto
      - mosquitto-clients
    state: present
  when: mosquitto_package_status.rc != 0 and ansible_distribution == 'Ubuntu'

- name: Copy mosquitto configuration file
  copy:
    src: mosquitto.conf
    dest: /etc/mosquitto/mosquitto.conf
    owner: root
    group: root
    mode: "0644"
  when: mosquitto_package_status.rc != 0
  notify: restart mosquitto

- name: Ensure mosquitto is enabled and started
  service:
    name: mosquitto
    enabled: yes
    state: started
  when: mosquitto_package_status.rc != 0
