name: Test Ansible

on:
  workflow_dispatch:

jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible script
        run: ansible-playbook -i inventory.ini palybook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
